<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(SolutionDir)\Directory.Build.props" />

    <!-- General Package Properties -->
    <PropertyGroup>
		<PackageId>$safeprojectname$</PackageId>
        <Version>0.0.1</Version>
        <Authors>Apkawa</Authors>
        <Copyright>$(AssemblyCopyright)</Copyright>
        <RepositoryUrl>https://github.com/Apkawa/Oni-Mods</RepositoryUrl>
    </PropertyGroup>


    <!-- Build Properties -->
    <PropertyGroup>
        <TargetFramework>net471</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <AssemblyName>$(PackageId)</AssemblyName>
        <RootNamespace>$(PackageId)</RootNamespace>
        <IsMod>true</IsMod>
        <GenerateMetadata>true</GenerateMetadata>
<!--        Enable if added external dll like PLib -->
        <IsPacked>true</IsPacked>
    </PropertyGroup>


    <!-- Mod Info -->
    <PropertyGroup>
        <ModName>$(PackageId)</ModName>
        <ModDescription/>
        <SupportedContent>ALL</SupportedContent> <!-- Use "EXPANSION1_ID" for dlc only -->
        <MinimumSupportedBuild>$(TargetGameVersion)</MinimumSupportedBuild>
        <APIVersion>2</APIVersion>
    </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\UtilLibs\UtilLibs.csproj" />
	</ItemGroup>

</Project>

