<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(SolutionDir)\Directory.Build.props" />
    
    <!-- General Package Properties -->
    <PropertyGroup>
        <PackageId>Example</PackageId>
        <Version>1.0.2</Version>
        <Authors>Apkawa</Authors>
        <Copyright>$(AssemblyCopyright)</Copyright>
        <RepositoryUrl>https://github.com/Apkawa/Oni-Mods</RepositoryUrl>
    </PropertyGroup>


    <!-- Build Properties -->
    <PropertyGroup>
        <TargetFramework>net471</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <AssemblyName>$(PackageId)</AssemblyName>
        <RootNamespace>$(PackageId)</RootNamespace>
        <IsMod>true</IsMod>
        <GenerateMetadata>true</GenerateMetadata>
<!--        Enable if added external dll like PLib -->
        <IsPacked>true</IsPacked>
    </PropertyGroup>


    <!-- Mod Info -->
    <PropertyGroup>
        <ModName>$(PackageId)</ModName>
        <ModDescription/>
        <SupportedContent>ALL</SupportedContent> <!-- Use "EXPANSION1_ID" for dlc only -->
        <MinimumSupportedBuild>535211</MinimumSupportedBuild>
        <APIVersion>2</APIVersion>
    </PropertyGroup>
    
    <PropertyGroup>
        <GameModDir>$(GameConfigDir)/mods/Dev/$(MSBuildProjectName)</GameModDir>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="PLib" Version="4.19.0" />
    </ItemGroup>


</Project>
